restart_file: .na
start_datetime: 2021-03-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2018-10-05 00:00:00
forecast_horizon: 3.0
sim_name: test_run
forecast_output_directory: /Users/heatherwander/Documents/VirginiaTech/research/BVR_GLM/BVRE-forecast/glm
forecast_configuration_directory: /Users/heatherwander/Documents/VirginiaTech/research/BVR_GLM/BVRE-forecast/glm
execute_directory: /Users/heatherwander/Documents/VirginiaTech/research/BVR_GLM/BVRE-forecast/working_directory

