restart_file: /Users/heatherwander/Documents/VirginiaTech/research/BVR_GLM/BVRE-forecast/glm/bvre_H_2019_07_15_2019_08_10_F_16_20210415T184123.nc
start_day_local: '2019-08-10'
start_time_local: '07:00:00'
end_day_local: .na
forecast_start_day_local: '2019-08-11'
forecast_horizon: 16.0
forecast_project_id: bvre_flare
sim_name: bvre
forecast_sss_on: no
forecast_location: /Users/heatherwander/Documents/VirginiaTech/research/BVR_GLM/BVRE-forecast/BVRE-data/NOAAGEFS_1hr/bvre
execute_location: /Users/heatherwander/Documents/VirginiaTech/research/BVR_GLM/BVRE-forecast/working_directory
