restart_file: /glm/output.nc
start_day_local: '2018-09-20'
start_time_local: '07:00:00'
end_day_local: .na
forecast_start_day_local: '2018-09-21'
forecast_horizon: 16.0
forecast_project_id: bvre_flare
sim_name: bvre
forecast_sss_on: no
forecast_location: /glm
execute_location: /working_directory
