restart_file: .na
start_day_local: '2021-03-01'
start_time_local: '07:00:00'
end_day_local: '2021-03-14'
forecast_start_day_local: '2021-03-15'
forecast_horizon: 16
forecast_project_id: bvre_flare
sim_name: bvre
forecast_sss_on: no
forecast_location: /Users/heatherwander/Documents/VirginiaTech/research/BVR_GLM/BVRE-forecast/glm
execute_location: /Users/heatherwander/Documents/VirginiaTech/research/BVR_GLM/BVRE-forecast/working_directory
